### ISSUE TITLE
Integration with ReCharge subscriptions

### ISSUE THREAD

**Issue by luth-er** [anujtenani/goaffpro#1]
Your docs state that GoAffPro integrates with ReCharge subscriptions. I have recently paid for a premium membership so that my affiliates can earn commission on subscriptions that customers pay for. However when a customer opts to pay via ReCharge there is no option to enter the affiliate discount code. I have followed all the steps provided in your docs and spent a day googling the answer, but to no avail. Could you please let me know how affiliates can earn their commission when a customer decides to set up a subscription payment?

**Comment by Rob-Foster** [comment]
I am also interested in this, particularly when the cart is composed of both subscription and one time purchase products. Please update me if you find the answer. thanks
robert at empreendify.com
