### ISSUE TITLE
Affliate didnot detect as their order or comission.

### ISSUE THREAD

**Issue by aimiazri88** [anujtenani/goaffpro#105]
Hi, 

We facing issue which our affliates didnot get commission from their link referral lately. Could you advice us?
So far, we got complaint around 30 from our affliate.
Here as one of the proof, as your CS at Facebook messenger request. 
Kindly, your feedback ASAP

![Conversation customer H23234](https://user-images.githubusercontent.com/75781310/101751223-ff11cb00-3b0a-11eb-9f9e-53379033511c.jpeg)
![Conversation customer H23234_1](https://user-images.githubusercontent.com/75781310/101751229-00db8e80-3b0b-11eb-8a87-625d197e21be.jpeg)
![image](https://user-images.githubusercontent.com/75781310/101751511-4dbf6500-3b0b-11eb-9ea0-27ce50c9daab.png)
![image](https://user-images.githubusercontent.com/75781310/101751575-62036200-3b0b-11eb-8c1b-ff6bfc578674.png)

**Comment by anujtenani** [comment]
Hi

The affiliate has an _ (underscore) at the end of the link (as evident by your affiliate's dashboard screenshot), but the affiliate is sharing the link without the underscore

Please check if the the link that they are sharing is correct.

**Comment by aimiazri88** [comment]
Hi, 

Thanks for inform that. already inform to our affliate.

Could you please check this too? Because i already check the link, and try its ok. but when customer use the link it does not detect at goaffpro. Really appreciate your reply.


![conversation with customer](https://user-images.githubusercontent.com/75781310/101986650-08956180-3cca-11eb-9577-c19ea97ac7f7.jpeg)
![conversation with customer_2](https://user-images.githubusercontent.com/75781310/101986651-09c68e80-3cca-11eb-94e0-3369d1aeed1c.jpeg)
![Affliate Dashboard - referral CodeNanaShafie](https://user-images.githubusercontent.com/75781310/101986667-28c52080-3cca-11eb-9149-47abf184bab7.JPG)
![Shopify tracking - referral Code=NanaShafie](https://user-images.githubusercontent.com/75781310/101986792-1ac3cf80-3ccb-11eb-9d91-2aa27006a363.JPG)
