### ISSUE TITLE
Requesting change to affiliate view

### ISSUE THREAD

**Issue by Varnu** [anujtenani/goaffpro#112]
![Commission](https://user-images.githubusercontent.com/76845831/103442601-acca5280-4c4f-11eb-8cd1-dbd4206d484e.JPG)

Hello, would it be possible to make a change to the affiliate dashboard view so that the total sales value does not include postage as we only pay commission on product sales and not postage.

Our affiliates are getting confused with how much they will be paid as our flat 20% is paid on products and not postage, in the picture example above the affiliate has made £576.67 in sales (Including postage) so they are expecting to make 20% which would be £115.33, however because postage makes up around £65 of this total amount the actual commission would be £102.33.

If there is a way to exclude postage from this figure it would allow affiliates to see and work out exactly how much they will earn by taking the figure and just working out what 20% is.

Thank you.

**Comment by Varnu** [comment]
Hello, does anyone pick these requests up or acknowledge them?

**Comment by anujtenani** [comment]
This feature is already in place.

You can choose sales reporting to ORDER SUBTOTAL in Settings -> Advanced
Settings tab to show the affiliate the amount on which their commission is
calculated.
