### ISSUE TITLE
Tracking from client side is hackable. Is it possible to send the conversion from Backend ?

### ISSUE THREAD

**Issue by bhavelyn** [anujtenani/goaffpro#119]
Hi,

I am trying to integrate this for offering affiliate program for our site.

Our site is custom built in Node/NextJS so I am using the Custom SDK option which is simple enough, but the issue is that the conversion is getting sent from the client side which someone could very easily reply and then it will start creating multiple commissions/orders on goAffPro side.

Do you provide a way to send the conversion from the server side ?

**Comment by anujtenani** [comment]
You can use the "Secure Payload" option in the Settings -> SDK Settings tab to send the Payload as JSON WebToken Encoded with your private key

More details here
https://github.com/anujtenani/goaffpro/wiki/Custom-Integration-advanced-guide#securing-payload
