### ISSUE TITLE
Customer Name/Email variable for Merchant Notification

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#120]
A merchant has asked for an option where they can see the customer name/email in the New Referral Sale email notification that they receive. 

![Screenshot 2021-02-07 213027](https://user-images.githubusercontent.com/42622335/107152111-1692f600-698c-11eb-8afb-85a4b9ddde1b.png)

**Comment by anujtenani** [comment]
The customer email variable is now available as 

{{order.customer_email}}
