### ISSUE TITLE
"Disable commission if customer is also an affiliate" option giving off unexpected error

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#121]
There have been a couple of merchants who have messaged regarding an issue where they seem to be missing out on sales. (Arent able to assign them too). 

The issue ,as I have checked is being caused by the "Disable commission if customer is also an affiliate" option (in Settings > General > Sales). That option is not letting sales get tracked, and when the sale is manually assigned, it gives a "UNEXPECTED ERROR" message. 

![Screenshot 2021-02-08 014149](https://user-images.githubusercontent.com/42622335/107196122-3a038280-6a18-11eb-8573-9e930f13e42d.png)

Till now, I have had three merchants raise this, I have temporarily unchecked that option for them and the sale are now back to getting tracked (and have also assigned the sales that they indicated, they missed). 

(I have sent further details over email)

**Comment by anujtenani** [comment]
Please try again. This issue should be fixed with latest update.

**Comment by palepaul** [comment]
I have checked this up for all the three merchants (assigned the sales after enabling the option). It is working now.
