### ISSUE TITLE
Network Tab Date Filter

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#122]
A merchant has requested if the Network tab in the affiliate dashboard can show data in the network summary table, the members and revenue table for particular dates with a date filter option. (or like a monthly, yearly and lifetime data option)

![image](https://user-images.githubusercontent.com/42622335/107418585-d9219a80-6b3c-11eb-83e1-88e2080007a9.png)

**Comment by Tony76092** [comment]
I think this is a real issue that goes beyond just the network page - it extents the homepage too. On the homepage you can select a date range to search but it naturally reverts to a view that displays activity overtime once you come out - when you are trying to motivate a Affiliate it is important that firstly they can see Month todate their results supported by an ability to date range - with this in mind I would strongly recommend the default always be MTD. This would also apply to the Network tab which at this time has no date range capability

**Comment by anujtenani** [comment]
This is fixed with the new network-explorer option. This allows affiliates to see their down lines sales in a particular date range.
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/1143211/112723545-2b741a80-8f35-11eb-95df-aab117f4e376.png">

Closing this issue. Kindly comment below in case of a suggestion or feedback on this new feature.

**Comment by Tony76092** [comment]
Thank you Anuj

I sent the following feedback to the team on the experience – I think there is an opportunity to further improve based on the following.

great to see new Network Explore feature - what can i do to ensure the default filter is Entire Team. Secondly on the example shown the default is set to show only active affiliates the challenge is in the case you only see all active affiliates when this is unchecked - see example on next extract –

***@***.***D72F96.637FAAB0]



Proposed Default  - Much better gives a more accuate picture of activity

***@***.***D72F96.637FAAB0]

Current – Default Show Active Affiliates Only  - this is working in reverse currently showing nothing

***@***.***D72F96.637FAAB0]

Proposed – the default should show the active network

***@***.***D72F96.637FAAB0]

Regards

Tony


Chief Operating Officer
Cell : 817 201 2404
www.welcel.com<http://www.welcel.com>

***@***.***D691B1.5EC0A250]
