### ISSUE TITLE
Auto-Assigning Affiliates into Commission Groups (based on memberships)

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#124]
A merchant has requested for an option where memberships plans can be linked to commission groups. So that, when an affiliate opts for a particular membership plan, they will automatically get assigned to the particular commission group (which has been linked to the membership plan).

I suppose an example here would be that if a plan advertises 15% commission to the affiliate, then the affiliates, after opting for this plan will be automatically added to the commission group that gives the 15% commission. (since that membership plan is linked to that particular affiliate group)

**Comment by anujtenani** [comment]
Added in the membership plans page. Can be set when editing or creating the
plan
