### ISSUE TITLE
GoAffPro: Parent ID variable added to email notifications

### ISSUE THREAD

**Issue by GTM-CRM** [anujtenani/goaffpro#126]
To connect our new affiliates to their parents in our CRM, we need to know the parent ID who enrolled the affiliate. Need a Parent ID variable available for Affiliate Email Notifications for new affiliates and/or for Zapier to access this information.

**Comment by anujtenani** [comment]
The following variables are now added in the email templating system

{{ parentAffiliate.name }}
{{ parentAffiliate.email }}
{{ parentAffiliate.id }}

Zapier hook for affiliate data is 
https://zapier.com/developer/public-invite/109290/cfb8a362fbafecb380e5f459cf259b86/
The information can also be obtained from API at https://api.goaffpro.com/docs/admin
