### ISSUE TITLE
Search Feature on Home Page

### ISSUE THREAD

**Issue by MLLOwner** [anujtenani/goaffpro#127]
I would like to request a Search feature on the Affiliate Dashboard homepage. Many customers delete their emails with their order numbers and when asked about their order my affiliates have to go through the orders 1 by 1 to find the order in question! A search feature would be AMAZING, ALSO please add the Customer Name to the Home Page beside the order #. Super helpful!!!!!!

**Comment by anujtenani** [comment]
Now available in the affiliate's dashboard (in the Order details widget)

Affiliates can search by order number or customer's email address to find the order.

<img width="1237" alt="Screenshot 2021-04-11 at 12 09 51 AM" src="https://user-images.githubusercontent.com/1143211/114281136-4f1d8180-9a5a-11eb-8775-4327dde48ba2.png">

**Comment by MLLOwner** [comment]
This is awesome news, but my affiliates have been trying it out and they are running into issues. Not all names are coming up in the search. 
 
Let me know when the bug is fixed, thank you.
 
 
-----Original Message-----

**Comment by MLLOwner** [comment]
Did you get my email? It's not searching all names. Has this been fixed?
 
 
-----Original Message-----
