### ISSUE TITLE
Assign Payment Option to Group

### ISSUE THREAD

**Issue by LeeorKabalik** [anujtenani/goaffpro#128]
Would you be able to create an option within Affiliate Groups to set payments options?
This would be extremely helpful since we have a couple different Affiliate Groups and each one has a different payment method (store credit vs payouts). Currently, I have to go one by one and change their payment settings because there's no bulk editor for payment method.

Thanks

**Comment by anujtenani** [comment]
The groups can be assigned payment methods now in the Groups configuration now.
See screenshot below
<img width="1104" alt="Screenshot 2021-06-05 at 11 01 45 AM" src="https://user-images.githubusercontent.com/1143211/120881274-8426fa00-c5ed-11eb-9ab8-8e32008c17c7.png">
