### ISSUE TITLE
Filter Affiliates by Group

### ISSUE THREAD

**Issue by melissawitt** [anujtenani/goaffpro#129]
I would love to be able to filter affiliates on the main Affiliates tab by the group they are in. It seems the only way to identify what group the affiliates are in is to go into the group itself. It would be handy to have an extra field available that tags them by group, and also available in the exported CSV file. Is that something that could be done?

**Comment by anujtenani** [comment]
Hi Melissa

I am categorizing the features into separate items

- [ ] Add Group Name in the affiliates export file
- [ ] Add group filter in all affiliates page
- [ ] Show affiliate's group name in affiliate details page

You can track the progress of the features in this thread. This issue will be closed when all 3 features are implemented.
