### ISSUE TITLE
Affiliates are not able to customize their coupon codes (WooCommerce)

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#13]
Affiliates are not able to customize their coupon codes in their dashboard, despite the option being enabled in the Look and Feel > Affiliate Toolbar > Tracking Modes > Allow affiliate to customize coupon code. 

![Annotation 2020-08-25 232408](https://user-images.githubusercontent.com/42622335/91210226-812bde80-e72a-11ea-93e5-d3f47ac80f9a.png)

![118516794_304791920775042_3567318136532488223_n](https://user-images.githubusercontent.com/42622335/91302822-ac630c00-e7c4-11ea-8d62-19907355029c.png)

**Comment by anujtenani** [comment]
Fixed with woocommerce 2.0 release
