### ISSUE TITLE
Bulk Email Groups option

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#130]
Merchants have requested an option in the Bulk Mail tab which would allow them to send emails to affiliate groups.

**Comment by VitoriVertrieb** [comment]
Hello together,
it would be very important for us to use this option as soon as possible. Could you please prefer this request?
Thank you in Advance.

I hope, you´ll have a nice day
Please contact me for more questions.

Kind regards

Florian
VITORI Vertrieb
Mail: vertrieb@vitori.de

**Comment by VitoriVertrieb** [comment]
Hello together,
it would be very important for us to use this option as soon as possible. Could you please prefer this request?
Thank you in Advance.

I hope, you´ll have a nice day
Please contact me for more questions.

Kind regards

Florian
VITORI Vertrieb
Mail: vertrieb@vitori.de

**Comment by AdamVasica** [comment]
I would love to have this feature as well. I thought of using GoAffpro for affiliates and for influencers at the same time, but both of these groups need to get different emails.

**Comment by palepaul** [comment]
Hello,

This option has been added now:

![image](https://user-images.githubusercontent.com/42622335/166691863-9df7a22c-a751-4926-837f-b4b66103e6ec.png)

Please see the marketing tab, where you can create campaigns and schedule emails too.

![image](https://user-images.githubusercontent.com/42622335/166691968-fcee628f-1207-4bd2-8088-08fc396d740a.png)

@AdamVasica @VitoriVertrieb
