### ISSUE TITLE
Undelivered Mail - Server is on Blacklist

### ISSUE THREAD

**Issue by minc21** [anujtenani/goaffpro#147]
Hi Goaffpro,

unfortunately your server is on outlooks block list -> mails are not delivered:

> host
    hotmail-com.olc.protection.outlook.com[104.47.58.33] said: 550 5.7.1
    Unfortunately, messages from [116.202.176.161] weren't sent. Please contact
    your Internet service provider since part of their network is on our block
    list (S3140). You can also refer your provider to
    http://mail.live.com/mail/troubleshooting.aspx#errors.
    [DM6NAM10FT054.eop-nam10.prod.protection.outlook.com] (in reply to MAIL
    FROM command)

**Comment by minc21** [comment]
Also on gmx.net blacklist:

> Diagnostic-Code: smtp; 554-gmx.net (mxgmx015) Nemesis ESMTP Service not
    available 554-No SMTP service 554-IP address is black listed. 554 For
    explanation visit
    https://postmaster.gmx.net/en/error-messages?ip=116.202.176.161&c=bip

**Comment by anujtenani** [comment]
Kindly switch the email service providers using the following steps
1. Open Settings -> Notifications tab -> FROM EMAIL section
2. Click Use Default to switch to default option
3. Click Change and then follow the steps provided to update the FROM email
