### ISSUE TITLE
Pre-determined text for sharing on social media (popup)

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#148]
A merchant has messaged regarding a feature request where they would like a per-determined text to get added to a social media post (like on Facebook or Twitter), when the social media icon is clicked on in the Advanced post checkout popup.

![image](https://user-images.githubusercontent.com/42622335/118409673-45b2b500-b6a9-11eb-9478-d2b80f004463.png)

The example he has given is of a third party service:

When the icon is clicked: 

![Screenshot 2021-05-17 004215](https://user-images.githubusercontent.com/42622335/118409737-8dd1d780-b6a9-11eb-95cd-51b8d14bdfdc.png)

It opens up Facebook or Twitter with some text (I am guessing that it is per-determined, what this text says and can be edited as per the merchant's choice)

Facebook:
![Screenshot 2021-05-17 003238](https://user-images.githubusercontent.com/42622335/118409699-6ed34580-b6a9-11eb-906d-a6c1fda8d9a2.png)

Twitter:
![Screenshot 2021-05-17 003510](https://user-images.githubusercontent.com/42622335/118409700-6f6bdc00-b6a9-11eb-92de-08697551b4d6.png)

The merchant has given an example that such a link opens up and the text gets added automatically:

https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fexample.com&quote=If+anyone+is+interested+in+getting+a+discount+at+store+please+feel+free+to+use+my+code+DISCOUNT+for+10%+off+of+any+purchase%21

**Comment by anujtenani** [comment]
This is available now for advanced type of post checkout popup

<img width="877" alt="Screenshot 2021-05-28 at 6 28 40 PM" src="https://user-images.githubusercontent.com/1143211/119987438-a8c61500-bfe2-11eb-94c7-26443dd94e00.png">
