### ISSUE TITLE
Affiliate Dashboard Widget (Adding Information)

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#15]
Raised by: Eza Israel Chikashvili
Portal: team.usfamarketing.com

When an affiliate is logged into the dashboard, the merchant can place any information into that the section where the commission breakdowns for the levels is shown. (Feature Request)

**Comment by anujtenani** [comment]
Discussed with the merchant. The merchant now plans to use the New custom page feature to display the custom infographic. Closing this issue for now
