### ISSUE TITLE
Goaff Pro Sr

### ISSUE THREAD

**Issue by LETSPLAYONTHEMOON** [anujtenani/goaffpro#152]
Hello, 

Were are using Goaff Pro.
We have 3 levels in our plan.
 
1st level: Coach Paillette => 20% commissions
2nd Quartz Coach level => 23% direct commissions and 6% commissions on my team (To access this level I must have recruited 4 people, if this is not the case my commission level will remain at 20%) we must therefore configure in Goaff the fact that to captivate this level I must have 4 members in my team.
3rd Amber Coach level => 25% direct commissions and 6% commissions on my team and 4% commissions on my team's team (To access this level I must have recruited 3 Coach Quartz, if not the case my commission level will remain at 23%) we must therefore configure in Goaff the fact that to captivate this level I must have 3 members in my team.
 
In Goaff Pro w can't setup this type of rules concerning the size of the team regarding the levels of commission.

Thank you in advance for your help.

**Comment by anujtenani** [comment]
Closing this issue, as this is being managed over email
