### ISSUE TITLE
Integrations

### ISSUE THREAD

**Issue by karnanishikha** [anujtenani/goaffpro#154]
We would like to integrate our mailing campaign system which is the Campaign Monitor.

From:Colin
Store ID:144995
Platform:sdk

**Comment by anujtenani** [comment]
Campaign monitor integration is now available in the Settings -> Integrations tab
<img width="1228" alt="Screenshot 2021-06-05 at 10 59 18 AM" src="https://user-images.githubusercontent.com/1143211/120881187-1a0e5500-c5ed-11eb-8bd8-872a99c57efc.png">
