### ISSUE TITLE
Payouts

### ISSUE THREAD

**Issue by karnanishikha** [anujtenani/goaffpro#158]
the option to sort payouts by payment type as well as amount... For instance... Our Ambassadors get paid via store gift card when they earn $25. I would love to be able to sort payouts by store gift card payment and $25+. As well as be able to see all the Venmo, CashApp or cheque people at once as well. To differentiate payouts by payment type.

 From:Alli FIelds
Store ID:33886
Platform:shopify

**Comment by anujtenani** [comment]
Payment method based filter is now available in the Payments page -> Pending pay
<img width="1293" alt="Screenshot 2021-06-05 at 5 44 13 PM" src="https://user-images.githubusercontent.com/1143211/120891334-accae600-c625-11eb-94a3-4a7661ec69dc.png">
ments tab.
