### ISSUE TITLE
changing membership plan 

### ISSUE THREAD

**Issue by karnanishikha** [anujtenani/goaffpro#162]
Can u plz tell how can we change the tag of the affiliate
For eg. During membership an affiliate signup with retailer tag but later he eligible for distributor
So in this case how can change the tag name

 everyone like promotion 
If someone join as executive than his next aim to become manager

**Comment by anujtenani** [comment]
Can be changed by activating the Membership plan widget in their settings tab. (Look & Feel -> Affiliate dashboard tab -> Membership management option)
<img width="1272" alt="Screenshot 2022-09-19 at 12 24 48 PM" src="https://user-images.githubusercontent.com/1143211/190963977-66b2af13-8d37-4129-baf7-7693242a282b.png">
