### ISSUE TITLE
Built in Contact Form isn't sending emails to admin

### ISSUE THREAD

**Issue by minc21** [anujtenani/goaffpro#17]
In Shopify app contact form mails aren't send.

**Comment by anujtenani** [comment]
Hi

Can you elaborate in this bug ? The contact form is for sending emails to our support channel. Perhaps a screenshot of the contact form will help.

**Comment by minc21** [comment]
Hi,
it's the contact form linkt in footer of affiliate dashboard:

![Snag_12aaf64e](https://user-images.githubusercontent.com/699470/91272601-418de280-e77c-11ea-994f-a0bdf0e26266.png)

**Comment by anujtenani** [comment]
It is working on our end. Please check if the emails are ending up in spam

**Comment by minc21** [comment]
checked spam without success. :-(
Every other mail from shopify and goaff app works. It's just this contact form that isn't delivered.
