### ISSUE TITLE
external check out zapier

### ISSUE THREAD

**Issue by karnanishikha** [anujtenani/goaffpro#170]
How about through Zapier, that would be even better, is it possible to send POST or GET request to track order?

zapier has option of course to send orderId, aff ref number and amount, but not sure if your api can accept it and assign the commission to affiliate.

If you could check that with your dev/server guys it would be great to know what exactly & how to send.

This kind of server to server tracking will be the only way of reporting conversions now. Has offers and rest of affiliate networks are supporting this for very very long time already.

If you could check on your side it would be great (the api reference you sent is for taking data out of your system and not for reporting conversions).

Shopify store is on:
Store.beltbro.com

Custom checkout is on:
Beltbro.com/store/checkout/...

**Comment by anujtenani** [comment]
Possible via API now 

https://api.goaffpro.com/docs/admin/#/sdk/post_sdk_track_conversion
