### ISSUE TITLE
affiliate dashboard

### ISSUE THREAD

**Issue by karnanishikha** [anujtenani/goaffpro#181]
Can we add the automatic coupon application to the Affiliate dashboard store as a future feature request?

**Comment by karnanishikha** [comment]
is it possible to see sales/commission for each product
Like this, but with sales/commissions amount $:
![bckljmnaghdbofgl](https://user-images.githubusercontent.com/85340600/122524389-5b085f80-d018-11eb-9ca9-3c4ff4847445.png)

**Comment by anujtenani** [comment]
Both the features are now implemented.
