### ISSUE TITLE
Product Sold Widget with Commission 

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#183]
An affiliate has requested that the "Product Sold" widget in the affiliate dashboard (from the Widgets and Analytics section), also include commission earned on each product. Currently it only shows the number of sales for each product, but the affiliate has requested, if it could also show the commissions earned for each product.

![bckljmnaghdbofgl](https://user-images.githubusercontent.com/42622335/122479445-b884b800-cfe8-11eb-80fd-77892db8dfeb.png)

**Comment by anujtenani** [comment]
Implemented in the recent update
