### ISSUE TITLE
commission modifier for specific product

### ISSUE THREAD

**Issue by karnanishikha** [anujtenani/goaffpro#186]
As spoken before, I want this:
For the 1 specific product (not whole order):
Purchase up to RM5000 - 10% commission
RM5000 and above - 15% commission

desmondng528@gmail.com

**Comment by anujtenani** [comment]
Available now.

<img width="613" alt="Screenshot 2022-09-19 at 12 28 33 PM" src="https://user-images.githubusercontent.com/1143211/190964552-1dabaf24-dad6-4918-8b34-328a8c48cd32.png">
