### ISSUE TITLE
Advanced Post Checkout Popup with Minimum Value

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#188]
A merchant has requested for an option where the customer can only register as an affiliate, if they make a minimum purchase of $50 on their store.

Can this requirement be applied to the advanced post checkout popup, where the popup only appears if the minimum value of the order is above a certain amount (set by the merchant), and the popup then automatically registers them as an affiliate

Thank You

**Comment by anujtenani** [comment]
This feature is now implemented.
<img width="1026" alt="Screenshot 2021-07-01 at 12 48 12 AM" src="https://user-images.githubusercontent.com/1143211/124018948-0e545980-da06-11eb-9192-79cbf35922cf.png">
