### ISSUE TITLE
Sales Search with Order Number

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#190]
A merchant has requested the option for searching the sales in the Sales > All Sales tab using the order number.

![image](https://user-images.githubusercontent.com/42622335/125158473-04152680-e18f-11eb-938c-f2d2d4842927.png)

**Comment by anujtenani** [comment]
This option is available now.

<img width="1277" alt="Screenshot 2021-08-23 at 8 06 24 PM" src="https://user-images.githubusercontent.com/1143211/130466139-9eba6e76-463a-4cfb-8ee8-04130389d585.png">
