### ISSUE TITLE
Please display additional columns in the response of this API (/v1/user/feed/orders)

### ISSUE THREAD

**Issue by QuasarZero** [anujtenani/goaffpro#197]
There are no **sub_id** in response, it's necessary for me.
And I also want to see **merchant name**, **click time** in the same API's return.

Please add these columns to response in this [API](https://api.goaffpro.com/docs/admin/#/user/get_user_feed_orders).
* sub id
* merchant name
* click time

Thank you!

**Comment by anujtenani** [comment]
The `site_id`, `sub_id`, `conversion_details` field are now added in the /user/feed/orders endpoint

`store_name` can be obtained from /user/sites API endpoint
