### ISSUE TITLE
different target bonus for groups

### ISSUE THREAD

**Issue by karnanishikha** [anujtenani/goaffpro#201]
Is there a way to set a target bonus for different groups? I see where you can boost commision by % within the group settings, but would like to have different target bonuses if possible. Thank you in advance.

From:Black Flag Cornhole
Store ID:133696
Platform:shopify

**Comment by anujtenani** [comment]
Target bonus can now be specified in the groups.

<img width="1081" alt="Screenshot 2021-08-15 at 10 16 04 PM" src="https://user-images.githubusercontent.com/1143211/129485976-3eaa47ad-cf11-4050-a99c-361d6d03bd72.png">
