### ISSUE TITLE
Group Specific Reports

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#204]
A merchant has requested for an option, where he can download group specific reports (so that the report only shows data of affiliates in that selected group)

![image](https://user-images.githubusercontent.com/42622335/129855793-38e47ed0-7512-41c0-a275-6529c7c80c72.png)

**Comment by anujtenani** [comment]
This option is now added in the app.
<img width="1265" alt="Screenshot 2021-08-18 at 1 20 44 PM" src="https://user-images.githubusercontent.com/1143211/129859540-94bb4fe0-806b-42d7-acae-b42bf913922c.png">
