### ISSUE TITLE
Referral And Network Commission Columns in the Summary Widget

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#208]
A merchant has requested for an option to show the the referral commission and the network commission separately in the Summary table widget (in the Home Tab of the affiliate dashboard)

![image](https://user-images.githubusercontent.com/42622335/131234280-891a1578-9676-4843-85b4-a19a08b9e2a2.png)

![image](https://user-images.githubusercontent.com/42622335/131234304-6eccec99-3fc2-4eb8-b880-c143abb907f3.png)

Thank You

**Comment by kennyWEE54** [comment]
Yes, we need these features!

**Comment by anujtenani** [comment]
Can be added by selecting "Sale Earnings" and "Bonus" in the summary widget. 

 
<img width="754" alt="Screenshot 2022-09-19 at 12 21 58 PM" src="https://user-images.githubusercontent.com/1143211/190963653-dd789963-b60c-489b-99eb-be11607b2a29.png">
