### ISSUE TITLE
Affiliate Manual Sales (Shopify)

### ISSUE THREAD

**Issue by DH-LDreyer** [anujtenani/goaffpro#209]
Orders are getting "manually" assigned to affiliates 'automatically'. I am the only person access to the manager portal of GoAffPro. I keep getting "manual conversions" sales allocated to the wrong affiliates. 
1 - I did not assign the orders manually, but it shows that it is a manual sale in the conversion column (Sales>All Sales) 
2 - Some of these orders should be assigned (i.e., the conversion should be 'customer-affiliate-connect') to other affiliates. 

* Why are there manual orders not assigned by me manually? 
* How does these orders "overwrite" the customer-affiliate-connect conversions? 

This is a huge security concern for my CEO. Is there a way to see/track the conversion from when the order was placed? For example, to see how the sale was manually added to an affiliate (date/time/place/IP Address or anything like that). 

For reference: 
Example order #31565 (ID 9800) 

Thank you so much.

**Comment by anujtenani** [comment]
Hi

The manual order assignment is triggered when the merchant, themselves assign the order via Sales -> All sales tab -> Create new sale manually option

OR

Triggers order assignment via the API (See Settings -> Advanced Settings tab -> Access tokens section)

You seem to have two active API keys there. If you are not using them, make sure you delete these access tokens.

The manual assignment  will override all other tracking modes as this is what is intended by the merchant when assigning the sale the the affiliate.
eg. Merchant tells the system to assign order number #1001 to affiliate A, the system will do exactly that. Does not matter if the customer is connected to another affiliate or not.

**Comment by DH-LDreyer** [comment]
Thank you for your prompt response Anuj. 
I only used the access tokens to integrate with Omnisend; but I will delete them to see if this is the issue then.
I do have a feeling that this is not the issue though since the Access tokens had nothing to do with sales orders, it was just used for the email addresses of the affiliates alone; but hopefully there were some interference somehow.

**Comment by DH-LDreyer** [comment]
Good day, 

The issue still persist. I deleted all the public access tokens. I also monitored the manager portal 24/7. 
I am the only one who have access to this portal and I have not assigned these orders manually: 
Order #31804
Manually allocated to Marike de Kock (not by me); Order should be connected to Elizna Nortje (previously connected). 

Order #31808
Must be Lauren Badenhorst but is manually connected to someone else (not by me). 

Will you please look into this; this have been an issue for a while now. It really is not me that is allocating this orders manually.

**Comment by anujtenani** [comment]
Hi

On further investigation, the manual connection is getting triggered by the tags in the order in your shopify account. Is there any reason for the order to be tagged with affiliate's referral code ? eg. #31565 has an order tag of "8", #31804 has an order tag of "6", which correspond to the affiliate's referral codes.

I mean, are these orders getting tagged automatically via script/code or are the orders tagged manually ?

**Comment by DH-LDreyer** [comment]
Hi Anuj, 

YES. That was the issue/interference. 
We "had" a a tag for a customer's "number of orders" on Shopify. 
We deleted those tags, and I monitored the sales orders on GoAffPro this week -> no issues after that. 

Thank you so much for your help! 

Kind Regards, 
Lente
