### ISSUE TITLE
Affiliate QR code in Welcome Email

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#213]
A merchant has requested for an option to send over affiliate QR codes in the welcome email (possibly a variable or something similar to do this)

**Comment by anujtenani** [comment]
This is now possible with the {{{affiliate.ref_qrcode}}} tag (can be used in the img src

See screenshots below
<img width="737" alt="Screenshot 2022-01-09 at 1 14 42 PM" src="https://user-images.githubusercontent.com/1143211/148673748-98b7c49a-c85d-4768-92c8-34974504224d.png">
<img width="501" alt="Screenshot 2022-01-09 at 1 14 52 PM" src="https://user-images.githubusercontent.com/1143211/148673747-0d11f415-9358-450a-96d5-c084dc507c8e.png">
<img width="586" alt="Screenshot 2022-01-09 at 1 15 05 PM" src="https://user-images.githubusercontent.com/1143211/148673745-f3278c55-119b-4920-9ec4-82638f11f6d4.png">
<img width="607" alt="Screenshot 2022-01-09 at 1 15 20 PM" src="https://user-images.githubusercontent.com/1143211/148673743-a4cd7f98-84a3-470f-9978-44197900ab0d.png">
