### ISSUE TITLE
Email option in the affiliate profile page

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#214]
A merchant has requested for an option to be added in the affiliate profile page so that an affiliate can be sent an email like: "Send an email to affiliate" (where they can get directed to the bulk email section and the affiliate's name is already selected as a recipient)

![image](https://user-images.githubusercontent.com/42622335/148661018-da849b06-579e-4b9a-aa2d-dfe66d373fe4.png)

**Comment by anujtenani** [comment]
Available in the admin panel now.
