### ISSUE TITLE
affiliate leader board ranks based on specified duration

### ISSUE THREAD

**Issue by karnanishikha** [anujtenani/goaffpro#223]
The rank of the best affiliate should not be set to all-time but to the last 365 days,
Store ID:116369
Platform:shopify

leaderboard show on the dashboard for just the current month
Store ID:108180
Platform:shopify

**Comment by anujtenani** [comment]
Closing as the merchant can now create custom leaderboards in the Analytics page of the app
<img width="1240" alt="Screenshot 2022-09-19 at 12 19 10 PM" src="https://user-images.githubusercontent.com/1143211/190963167-c07ecba1-076d-456e-9cce-462289605a64.png">
