### ISSUE TITLE
Payment information Sync

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#229]
A merchant has requested if the payment information from Shopify can also be viewed within GoAffPro admin panel too (screenshot below):

![Payment info](https://user-images.githubusercontent.com/42622335/190946912-12a001ce-4586-4430-94d9-29771005fdd8.png)

(They say that this would allow them to accept/reject sales manually in GoAffPro without going to Shopify to check this)

**Comment by anujtenani** [comment]
Merchants can click on the order number -> and then select View in Shopify to open the Shopify order

Due to API rate limitations, fetching the live payment info data from Shopify can have issues.

**Comment by palepaul** [comment]
Got it. Thank You
