### ISSUE TITLE
Edit the quick links text

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#232]
A merchant has requested for an option to edit the "Quick Links" text in the affiliate dashboard (through the edit translations option):

![image](https://user-images.githubusercontent.com/42622335/190947712-d8a09491-33a6-465c-ada1-3b99ac2260b8.png)

If it can be added as an option to be edited:

![image](https://user-images.githubusercontent.com/42622335/190947703-1b412a98-8774-4978-b42d-c0258e451b64.png)

**Comment by anujtenani** [comment]
Added.
