### ISSUE TITLE
Verification Email not getting sent automatically (WooCommerce)

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#24]
The verification email is not getting sent our automatically, it only getting sent out manually when the Resend Email option is clicked in the affiliate dashboard

**Comment by anujtenani** [comment]
Hi Paul

Can you let me know of the affiliate portal URL where you tested this ?

**Comment by palepaul** [comment]
https://bliscent.goaffpro.com/

**Comment by anujtenani** [comment]
Fixed
