### ISSUE TITLE
The "Secure Payload" option doesn't seem to work.

### ISSUE THREAD

**Issue by rubby-c** [anujtenani/goaffpro#244]
I'm trying to send a request to https://api.goaffpro.com/v1/sdk/track/conversion from my backend once a Stripe purchase has been verified. With "Secure Payload" disabled, sending a POST with the following body works:
`
{
    "order": {
      "number": "1",
      "total": 24.99
    },
    "ref": "E2PToRt9NFktv"
}
`

![image](https://github.com/anujtenani/goaffpro/assets/80776684/8c6f89e2-1977-4b34-97af-c7f9550a66d0)

![image](https://github.com/anujtenani/goaffpro/assets/80776684/806344ab-ed8d-485c-ad6c-1f8d2fbde8bc)

I then enabled the option. Sending a request with a JWT token generated from my backend resulted in an error so I tried using [JWT.io](https://jwt.io/) and the Payload tester to generate a token with the secret key provided in the dashboard and sent a request with the token in the body. I'm getting the same error:

`
{
    "error": "The payload is invalid. Please ensure that the payload is encrypted with the correct secret key in the Settings -> SDK Settings tab of admin panel"
}
`

**Comment by anujtenani** [comment]
Hi

The payload data should just be the order object (see screenshot below)
<img width="1204" alt="Screenshot 2023-06-04 at 3 06 39 PM" src="https://github.com/anujtenani/goaffpro/assets/1143211/75c99e0d-d51a-453a-af8b-235422bc23c8">

Here is a sample jwt encoded with your store's key to test this out. 

```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJudW1iZXIiOiIxIiwidG90YWwiOjI0Ljk5fQ.wqpIzYhNuHFEuBTPj_XSdTvwhFzJVlQXGpt59_mpuq4
```

The API call should be something like

```http
POST https://api.goaffpro.com/v1/sdk/track/conversion
x-goaffpro-public-token: your-public-token
content-type: application/json

{
  "ref":"referral-code",
  "order":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJudW1iZXIiOiIxIiwidG90YWwiOjI0Ljk5fQ.wqpIzYhNuHFEuBTPj_XSdTvwhFzJVlQXGpt59_mpuq4"
}

```



Notes: 
1. The /v1/sdk/track/conversion call is intended for client side. i.e. calling the API from the browser
2. For server side calls you can avoid the JWT complexity by sending the order data and referral code directly to /v1/admin/orders endpoint

https://api.goaffpro.com/docs/admin/#/orders/post_admin_orders

**Comment by rubby-c** [comment]
Thank you! /v1/admin/orders is exactly what I needed, my integration works perfectly now.
