### ISSUE TITLE
"Profile Updated" message translation 

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#36]
A merchant has messaged regarding the message "Profile Updated" that appears in the affiliate dashboard when the profile is updated. This message cannot be translated using the Edit Translations option and it is also not getting automatically translated to the set portal language. 

![Annotation 2020-08-28 181437](https://user-images.githubusercontent.com/42622335/91562554-01388b00-e95b-11ea-869f-99af4092fcd1.png)

**Comment by anujtenani** [comment]
Fixed now
