### ISSUE TITLE
Email Template Bugs

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#37]
A merchant has highlighted these bugs that she is getting in the emails templates:

1. Order updated shows this code when sent to clients "{btn_dashboard | Tableau de bord}"

![Inked118615110_394629384856647_1475485851607393688_n_LI](https://user-images.githubusercontent.com/42622335/91579495-57142f80-e969-11ea-9269-d9a48296ae56.jpg)

2. Payment processed email shows only code when sent to clients

![Inked118656426_308789017049656_901566414463394904_n_LI](https://user-images.githubusercontent.com/42622335/91579728-ae1a0480-e969-11ea-8063-d4e669eff36f.jpg)

**Comment by anujtenani** [comment]
- 1 - This can be fixed by updating the content of the emails
Settings -> Notifications tab -> Customize templates -> Order updated email -> Update the text and remove {btn_dashboard.. text.

- 2 -  Is fixed now.
