### ISSUE TITLE
PayPal Payouts Negative Value Bug

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#42]
A merchant has highlighted that he was getting a validation error because of two negative values being show in the payouts "Review and Confirm" window. The negative values shouldn't technically be there, as the minimum payout filter is by default set to 0. The issue was resolved by changing the minimum amount filter to 1, and the negative records disappeared. 

I have sent you the full screenshot of it via email (as it contained confidential information)

![118652597_316665313009675_4315276604055366640_n](https://user-images.githubusercontent.com/42622335/91711637-d12ff880-eba3-11ea-8329-9fecb45f0faa.png)

**Comment by anujtenani** [comment]
Fixed in development branch. Update will be available by 7th September Milestone
