### ISSUE TITLE
Coupons Created in GoAffPro not working (WooCommerce)

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#47]
The coupons that are created in GoAffPro are not working in the store checkout, that are coming up an not valid. 

To add to this:
The same coupons however, if are created in WooCommerce panel as well, do work and are getting tracked in the app (as the custom coupons should be).

**Comment by palepaul** [comment]
This is happening in the store: bliscent.com 

The code created for the affiliate John Paul: johnpaul10 doesnt work (it shows up as not valid) 
(However codes that are created in WooCommerce are getting both applied and tracked by the app)

![Annotation 2020-09-04 223239](https://user-images.githubusercontent.com/42622335/92267682-a5dc3f00-eefe-11ea-8b26-3777d20a228a.png)

**Comment by anujtenani** [comment]
Closing. This is quite old. Re-open if the merchant is still having issues
