### ISSUE TITLE
Affiliates List - download button disapeard 

### ISSUE THREAD

**Issue by minc21** [anujtenani/goaffpro#51]
Today the download button on Affiliates grid disappeared?!

![Snag_25ba19a2](https://user-images.githubusercontent.com/699470/92397717-94c24680-f127-11ea-9551-3f9034ce46c3.png)

![Snag_25ba8fdb](https://user-images.githubusercontent.com/699470/92397753-a6a3e980-f127-11ea-9192-66768890ae87.png)

**Comment by anujtenani** [comment]
You can download this from Settings -> Reports tab. The table is limited to 250 affiliates for performance reasons.

**Comment by minc21** [comment]
OK, thank you.
Anyhow the download button shows up for a second and disappears when site is loaded. Doesn't look right.
