### ISSUE TITLE
Affiliates list- more controll on grid - sort columns, change columns order

### ISSUE THREAD

**Issue by minc21** [anujtenani/goaffpro#52]
Would be nice to have cols sortable!

**Comment by anujtenani** [comment]
Hi

1. TICK on the Gear icon below the sales table to change column order
2. You can sort some columns (like revenue, commission etc.), by clicking in the heading

**Comment by minc21** [comment]
Ok, I only tried to drag them. Remove and add in desired order does the trick!
Thanks
