### ISSUE TITLE
Input Field: Cursor Jumps / in Manage -> Affiliates -> Settings (shopify)

### ISSUE THREAD

**Issue by minc21** [anujtenani/goaffpro#58]
The Input fields (e.g. Your Name) show a strange behavior:

Let's say the filed has as value: John Doe
Now I try to change it to John Jay Doe
So I put my cursor on the position between John and Doe and I start to write "Jay"
I end up with "John JDoeay "

In principle the cursor jumps to the end of the input value after the first letter is put in!

**Comment by anujtenani** [comment]
Fixed in the recent update
