### ISSUE TITLE
Easier Access to Affiliate Commissions section 

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#60]
Many merchants have wanted to set up commissions for a group of affiliates directly. They can do so using the Affiliate Commissions section in the Commissions tab. 

However, currently, the only way of enabling the Affiliate Commissions section (or that it appears) is by asking merchants to set a standard commission for an affiliate by going to that affiliate's profile. Is there a way to enable the affiliate commissions section without doing this process? 

![Annotation 2020-09-10 022810](https://user-images.githubusercontent.com/42622335/92654657-c4cb3e80-f30d-11ea-8c2c-016354f27a2f.png)

**Comment by anujtenani** [comment]
#43 Would resolve this issue. Allowing for merchants to create affiliate commission groups

For now, we will enable the affiliate commissions section in the Commissions page by default, so that this feature's visibility increases.

**Comment by anujtenani** [comment]
Fixed in development branch. Update will be available in next 12 hours.
