### ISSUE TITLE
Password Link has Expired Issue

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#62]
Multiple merchants have messaged that when their affiliates are trying to reset their account passwords using the Forgot Password option, the affiliates are getting the error "Password Link has expired" when they open the link that is sent to them through the email. 

I have sent an email with more details (sharing the details over email for the merchant's privacy)

**Comment by palepaul** [comment]
Attaching screenshots from merchants for reference
![Screenshot 2020-09-13 005145](https://user-images.githubusercontent.com/42622335/93003336-6c897c00-f55b-11ea-9a04-b9a3e4e2f1d9.png)

![Screenshot 2020-09-13 005148](https://user-images.githubusercontent.com/42622335/93003335-6abfb880-f55b-11ea-8a68-db059d6fa0ad.png)

**Comment by anujtenani** [comment]
Validity of password expiration link now set to 3 days.
