### ISSUE TITLE
Footer shows up in some pages of the portal even after hiding

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#64]
A merchant has messaged that when the footer options is toggled to Hide in the affiliate portal (from the Look and Feel > Landing Page > Footer section). While the portal's footer does get hidden for the Landing page, Create Account page and the Login page, however the footer still appears for the Commissions, Tools, Reports, Privacy Policy and Terms and Conditions page. 

(The screenshot below are from the test portal, where the footer still appears for the other pages, but doesn't for the Landing page after it is toggled to Hide.)

![Screenshot 2020-09-13 003939](https://user-images.githubusercontent.com/42622335/93003142-cab55f80-f559-11ea-8516-5954ce6bcb71.png)
![Screenshot 2020-09-13 003922](https://user-images.githubusercontent.com/42622335/93003143-cc7f2300-f559-11ea-8a64-73ae66e5a0a4.png)

The merchant who has raised this issue, has embedded the portal in their store. 
(I have sent screenshots and details of the merchant's portal over email for the merchant's privacy)

**Comment by palepaul** [comment]
An addition to this issue is that the social media logins (Facebook and Google) are not appearing in the embedded portal (even though they are enabled)

![Screenshot 2020-09-13 043025](https://user-images.githubusercontent.com/42622335/93006442-edf00700-f579-11ea-81e8-1094085211fd.png)

![Screenshot 2020-09-13 043035](https://user-images.githubusercontent.com/42622335/93006443-efb9ca80-f579-11ea-94e7-cf41b0bc6bb7.png)

**Comment by anujtenani** [comment]
Fixed now
