### ISSUE TITLE
"Free Shipping" in the Discount value (for affiliate's information) option (for custom coupons)

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#72]
A merchant has messaged saying that "how to make a coupon for free delivery instead of the discount percentage?"

For now, when custom coupons (created in Shopify) are assigned to affiliates within the app, they can only be set up with either discount percentage or discount amount options in the "Discount value (for affiliate's information)" field. Can the option of Free Shipping be added to this as well (just like in Personal Coupon option). 

Otherwise, for now the only way for the merchant to assign a free delivery coupon to an affiliate (and show that it is a free delivery coupon) is to do it through personal coupon option and then edit the dashboard text using Affiliate Portal Language > Edit Translations. 

![Screenshot 2020-09-30 164754](https://user-images.githubusercontent.com/42622335/94678815-b8e70100-033c-11eb-9591-3a00fafa1a41.png)

**Comment by anujtenani** [comment]
The same feature is now also available in the Referral Coupon popup
