### ISSUE TITLE
All Affiliate section keeps on loading if there are no affiliate accounts 

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#75]
A merchant has messaged that in the Affiliates > All Affiliates section, if all the affiliates are deleted, then the page just keeps on loading. 

It prevents the merchant from creating an affiliate account from within GoAffPro as well.

(Since the All Affiliates page, was not working, creating an account through the create account page, does make the All Affiliates page show up, with that account in the table
However, when there are no accounts the page keeps on loading.)

![20201005_010313](https://user-images.githubusercontent.com/42622335/95025343-97707700-06a6-11eb-9d48-d113c12c12e0.jpg)

**Comment by anujtenani** [comment]
Thanks for the bug report. This is fixed in the latest update.
