### ISSUE TITLE
Affiliate Exceptions in Targets and Commission Boosters

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#78]
A merchant has requested for an option to set affiliates as exceptions on targets and commission boosters. So that these affiliates do not get the bonus or boost. 

(Earlier there were requests by merchants, on an option to create targets and commission boosts only for specific affiliates as well).

**Comment by NotProfane** [comment]
Yes would love to see that feature!

**Comment by palepaul** [comment]
**Update on this:**

The "Affiliate Groups" feature allows the merchants to create affiliate groups, these groups can also have their own commission boosters. 

This effectively resolves the commission booster exception issue, using the Affiliate Groups option, the merchant can create groups of affiliates for whom the booster will apply, the booster will not be applicable to affiliates outside the group.
