### ISSUE TITLE
Coupon Code Blacklist

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#79]
A merchant has requested for an option where he can blacklist coupon codes (so that affiliates cannot set those codes for themselves, as he has the option "Allow affiliate to customize coupon code" enabled). 

For now a workaround, I have told him, is to create a a dummy affiliate account and assign those codes to that affiliate (this will prevent other affiliates from setting those codes for themselves).

**Comment by anujtenani** [comment]
Allow affiliate to customize coupon code does not permit the affiliates to "assign" the coupon codes which already exist in the store to themselves.

For other use cases, the dummy account + coupon codes combo should work.
