### ISSUE TITLE
Information to add to order overwrites other cart attribute

### ISSUE THREAD

**Issue by minc21** [anujtenani/goaffpro#80]
Hi Goaff,
I'd like to use "Information to add to order" to add the affiliate to my admin order mail. Unfortunately this seems to overwrite my other cart-attribute.

Is this a bug? Or how do I get the information into my admin mail without overwriting other cart attributes?

cheers

**Comment by minc21** [comment]
Hi Goaff,
It would really be great to have the affiliate information in admin confirmation mail. "information to add to order" would solve that, but this function overwrites the other cart attributes. Could you please have a look?
thanks

**Comment by minc21** [comment]
No chance to get affiliate info into confirmation mail?

**Comment by anujtenani** [comment]
The cart attributes and order details are appended to existing tags and additional information fields
