### ISSUE TITLE
Parent affiliates viewing sales and commission for each affiliate under them

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#87]
A merchant has requested for an option to allow parent affiliates to see the the sales, revenue and commission of each affiliate under them. 

Currently, the parent affiliate is only able to view this information for each level, however the merchant has suggested that the parent affiliate be allowed an option to view the this information for each affiliate under them.

**Comment by hadstyle** [comment]
All for this, also 👍🏼

**Comment by bathcab** [comment]
Also been asked for this

**Comment by anujtenani** [comment]
Network explorer now available in the affiliate's dashboard -> network tab

This gives the affiliate access to sales data of their downlines

<img width="1213" alt="Screenshot 2021-03-27 at 6 55 59 PM" src="https://user-images.githubusercontent.com/1143211/112722214-1fd12580-8f2e-11eb-8857-9c39088aa285.png">

Closing this issue. If more refinements to this feature are required kindly comment below
