### ISSUE TITLE
Reset Password of Manager Account

### ISSUE THREAD

**Issue by Bejelly** [anujtenani/goaffpro#94]
How do I reset the password of the Manager Account? There is no button that allows me to do that.

**Comment by palepaul** [comment]
Hello @Bejelly, currently there isnt an option to reset the manager account password. 

It is recommended that you go to Settings > Extras > Manager (in GoAffPro) there click on the manager account to see the password. (Use the merchant account access from your platform's dashboard) 

If you arent able to do so, send in an email at admin@goaffpro.com with your credentials (email address, store URL and affiliate portal URL) so our team can send you the password of your manager account.
