### ISSUE TITLE
Two store IDs active 

### ISSUE THREAD

**Issue by skycherry11** [anujtenani/goaffpro#97]
We recently changed primary URL of our website 
And when we migrated to new site, goaffpro was reinstalled. While reinstalling, we used new email address and it got installed.mutilple problms followed  by that...

However, completely diff store got installed. And of we login to old master login old Goaffpro dashboard,  details etc visible and on our sore completely new store ID, every data has to b copied etc...

Is there a way to maintain only one store ID, one mail and delete the rest of data. Also how to configure API keys ..it doesn't give option to automatically install or manual plugin when clicking on goaffpro.. automatically signing to old email and taking to old dashboard . No pblm is , data can b seen from master login..but real the sales not updated as site shows Goaffpro with a diff store ID. 

Why Goaffpro is not giving an option to delete the data once the affiliate pgm is no longer needed. 

Please reply.

**Comment by anujtenani** [comment]
Merchant specific issue. Closing.
