### ISSUE TITLE
Product Sold Widget Issue

### ISSUE THREAD

**Issue by palepaul** [anujtenani/goaffpro#99]
A merchant has messaged regarding an issue they are having with the "Show Products Sold" widget. 

The widget isnt displaying anything in the affiliate dashboard. (Screenshot attached below).

![20201204_131931](https://user-images.githubusercontent.com/42622335/101136467-61faf200-3633-11eb-8141-44e3eaeee0ba.jpg)

(Additional details have been sent over email, for the merchant's privacy)

**Comment by palepaul** [comment]
Another merchant has raised this issue, they too cannot see the any value in the Product Sold widget.

**Comment by anujtenani** [comment]
Fixed in the latest update
